{{- if .Values.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    {{- include "finpay.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ .Files.Get "files/loki/config.yaml" | nindent 4 }}
{{- end }}
