apiVersion: v1
kind: Service
metadata:
  name: otelcol-gateway
  labels:
    {{- include "finpay.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: otelcol-gateway
  ports:
    - name: otlp-grpc
      port: {{ .Values.otelcol.service.otlpGrpcPort }}
      targetPort: otlp-grpc
    - name: otlp-http
      port: {{ .Values.otelcol.service.otlpHttpPort }}
      targetPort: otlp-http
    - name: metrics
      port: {{ .Values.otelcol.service.metricsPort }}
      targetPort: metrics
    - name: health
      port: {{ .Values.otelcol.service.healthPort }}
      targetPort: health
