global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: otelcol-gateway
    static_configs:
      - targets: ["otelcol-gateway:8888"]
  - job_name: finpay-api
    static_configs:
      - targets: ["finpay-api:2112"]
